// ============================================================
// AnchorAI — Learn Page (Resource Library)
// AI-curated educational recovery resource cards
// ============================================================
'use client';

export const dynamic = 'force-dynamic';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import BottomNav from '@/components/BottomNav';
import { getProfile } from '@/lib/store';
import type { ResourceCard } from '@/lib/types';

const topicIcons: Record<string, string> = {
  Cravings: '🧠',
  Family: '👨‍👩‍👧',
  Treatment: '💊',
  Support: '🤝',
  Prevention: '🛡️',
  default: '📖',
};

const topicColors: Record<string, string> = {
  Cravings: 'from-[#8b5cf6]/20 to-[#8b5cf6]/5',
  Family: 'from-[#f59e0b]/20 to-[#f59e0b]/5',
  Treatment: 'from-[#3b82f6]/20 to-[#3b82f6]/5',
  Support: 'from-[#22c55e]/20 to-[#22c55e]/5',
  Prevention: 'from-[#ef4444]/20 to-[#ef4444]/5',
  default: 'from-[#64748b]/20 to-[#64748b]/5',
};

export default function LearnPage() {
  const router = useRouter();
  const [cards, setCards] = useState<ResourceCard[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedCard, setExpandedCard] = useState<number | null>(null);

  useEffect(() => {
    if (!getProfile()) {
      router.replace('/');
      return;
    }

    fetchResources();
  }, [router]);

  const fetchResources = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/resources');
      if (res.ok) {
        const data = await res.json();
        setCards(data.cards || []);
      }
    } catch {
      // Will show empty state
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen pb-24 relative overflow-hidden">
      <div className="glow-orb w-72 h-72 bg-[#3b82f6] top-[-120px] left-[-60px] opacity-10" />

      <div className="max-w-lg mx-auto px-5 pt-8 relative z-10">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-white">Learn</h1>
          <p className="text-[#64748b] text-sm mt-1">
            AI-curated resources for your recovery journey
          </p>
        </div>

        {/* AI badge */}
        <div className="glass-card p-3 mb-6 flex items-center gap-2">
          <span className="text-sm">✨</span>
          <p className="text-xs text-[#94a3b8]">
            Content generated by <span className="text-[#22c55e] font-medium">Google Gemini</span> — evidence-based, stigma-free
          </p>
        </div>

        {/* Loading state */}
        {loading && (
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="glass-card p-5 shimmer h-32 rounded-2xl" />
            ))}
          </div>
        )}

        {/* Resource cards */}
        {!loading && (
          <div className="space-y-4">
            {cards.map((card, i) => (
              <button
                key={i}
                onClick={() => setExpandedCard(expandedCard === i ? null : i)}
                className={`resource-card glass-card p-5 w-full text-left bg-gradient-to-br ${topicColors[card.topic] || topicColors.default} cursor-pointer`}
              >
                <div className="flex items-start gap-3">
                  <span className="text-2xl mt-0.5">
                    {topicIcons[card.topic] || topicIcons.default}
                  </span>
                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <h3 className="font-semibold text-white text-base">
                        {card.title}
                      </h3>
                      <span className="text-xs text-[#64748b] ml-2 whitespace-nowrap">
                        {card.readTime} min read
                      </span>
                    </div>
                    <p className="text-sm text-[#94a3b8] mt-2 leading-relaxed">
                      {card.summary}
                    </p>

                    {expandedCard === i && (
                      <div className="mt-4 pt-4 border-t border-[rgba(255,255,255,0.06)] animate-fade-in">
                        <p className="text-xs uppercase tracking-wider text-[#22c55e] font-semibold mb-2">
                          💡 Action for today
                        </p>
                        <p className="text-sm text-[#e2e8f0]">
                          {card.practicalTip}
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </button>
            ))}
          </div>
        )}

        {/* Empty state */}
        {!loading && cards.length === 0 && (
          <div className="text-center py-12">
            <p className="text-4xl mb-4">📚</p>
            <p className="text-[#94a3b8]">Resources will appear here once generated.</p>
            <button
              onClick={fetchResources}
              className="mt-4 px-6 py-2 rounded-xl bg-[#22c55e] text-white text-sm font-medium hover:bg-[#16a34a] transition-all"
            >
              Generate Resources
            </button>
          </div>
        )}
      </div>

      <BottomNav />
    </div>
  );
}
